// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment_categories.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createEquipmentCategory = `-- name: CreateEquipmentCategory :one
INSERT INTO equipment_categories (name, description, created_by, updated_by)
VALUES ($1, $2, $3, $3)
RETURNING id, name, description, created_at, updated_at, deleted_at, created_by, updated_by
`

type CreateEquipmentCategoryParams struct {
	Name        string
	Description *string
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateEquipmentCategory(ctx context.Context, arg CreateEquipmentCategoryParams) (EquipmentCategory, error) {
	row := q.db.QueryRow(ctx, createEquipmentCategory, arg.Name, arg.Description, arg.CreatedBy)
	var i EquipmentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listEquipmentCategories = `-- name: ListEquipmentCategories :many
SELECT id, name, description, created_at, updated_at, deleted_at, created_by, updated_by
FROM equipment_categories
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListEquipmentCategories(ctx context.Context) ([]EquipmentCategory, error) {
	rows, err := q.db.Query(ctx, listEquipmentCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentCategory
	for rows.Next() {
		var i EquipmentCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEquipmentCategory = `-- name: SoftDeleteEquipmentCategory :exec
UPDATE equipment_categories
SET deleted_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteEquipmentCategoryParams struct {
	ID        int32
	UpdatedBy *uuid.UUID
}

func (q *Queries) SoftDeleteEquipmentCategory(ctx context.Context, arg SoftDeleteEquipmentCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteEquipmentCategory, arg.ID, arg.UpdatedBy)
	return err
}

const updateEquipmentCategory = `-- name: UpdateEquipmentCategory :one
UPDATE equipment_categories
SET name = $2,
    description = $3,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpdateEquipmentCategoryParams struct {
	ID          int32
	Name        string
	Description *string
	UpdatedBy   *uuid.UUID
}

func (q *Queries) UpdateEquipmentCategory(ctx context.Context, arg UpdateEquipmentCategoryParams) (EquipmentCategory, error) {
	row := q.db.QueryRow(ctx, updateEquipmentCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UpdatedBy,
	)
	var i EquipmentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
