// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment_category_links.sql

package queries

import (
	"context"
)

const clearEquipmentCategories = `-- name: ClearEquipmentCategories :exec
DELETE FROM equipment_category_links
WHERE equipment_id = $1
`

func (q *Queries) ClearEquipmentCategories(ctx context.Context, equipmentID int32) error {
	_, err := q.db.Exec(ctx, clearEquipmentCategories, equipmentID)
	return err
}

const listCategoriesForEquipment = `-- name: ListCategoriesForEquipment :many
SELECT c.id, c.name, c.description, c.created_at, c.updated_at, c.deleted_at, c.created_by, c.updated_by
FROM equipment_categories c
         JOIN equipment_category_links l ON c.id = l.category_id
WHERE l.equipment_id = $1 AND c.deleted_at IS NULL
`

func (q *Queries) ListCategoriesForEquipment(ctx context.Context, equipmentID int32) ([]EquipmentCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesForEquipment, equipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentCategory
	for rows.Next() {
		var i EquipmentCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEquipmentCategories = `-- name: UpsertEquipmentCategories :exec
INSERT INTO equipment_category_links (equipment_id, category_id)
VALUES ($1, UNNEST($2::INT[]))
ON CONFLICT (equipment_id, category_id) DO NOTHING
`

type UpsertEquipmentCategoriesParams struct {
	EquipmentID int32
	Column2     []int32
}

func (q *Queries) UpsertEquipmentCategories(ctx context.Context, arg UpsertEquipmentCategoriesParams) error {
	_, err := q.db.Exec(ctx, upsertEquipmentCategories, arg.EquipmentID, arg.Column2)
	return err
}
