// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const CreateEquipment = `-- name: CreateEquipment :one
INSERT INTO equipment (name, description, quantity, created_by, updated_by)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, name, description, quantity, created_at, updated_at, deleted_at, created_by, updated_by
`

type CreateEquipmentParams struct {
	Name        string
	Description *string
	Quantity    int32
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, CreateEquipment,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.CreatedBy,
	)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const GetEquipmentByID = `-- name: GetEquipmentByID :one
SELECT id, name, description, quantity, created_at, updated_at, deleted_at, created_by, updated_by
FROM equipment
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipmentByID(ctx context.Context, id int32) (Equipment, error) {
	row := q.db.QueryRow(ctx, GetEquipmentByID, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const ListEquipment = `-- name: ListEquipment :many
SELECT id, name, description, quantity, created_at, updated_at, deleted_at, created_by, updated_by
FROM equipment
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListEquipment(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, ListEquipment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteEquipment = `-- name: SoftDeleteEquipment :exec
UPDATE equipment
SET deleted_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteEquipmentParams struct {
	ID        int32
	UpdatedBy *uuid.UUID
}

func (q *Queries) SoftDeleteEquipment(ctx context.Context, arg SoftDeleteEquipmentParams) error {
	_, err := q.db.Exec(ctx, SoftDeleteEquipment, arg.ID, arg.UpdatedBy)
	return err
}

const UpdateEquipment = `-- name: UpdateEquipment :one
UPDATE equipment
SET name = $2,
    description = $3,
    quantity = $4,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, quantity, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpdateEquipmentParams struct {
	ID          int32
	Name        string
	Description *string
	Quantity    int32
	UpdatedBy   *uuid.UUID
}

func (q *Queries) UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, UpdateEquipment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.UpdatedBy,
	)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
