// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package queries

import (
	"context"
)

const addPlace = `-- name: AddPlace :one
INSERT INTO places (name, description, latitude, longitude)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, latitude, longitude, created_at, updated_at
`

type AddPlaceParams struct {
	Name        string
	Description *string
	Latitude    float64
	Longitude   float64
}

func (q *Queries) AddPlace(ctx context.Context, arg AddPlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, addPlace,
		arg.Name,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaces = `-- name: GetPlaces :many
SELECT id, name, description, latitude, longitude, created_at, updated_at FROM places
ORDER BY created_at DESC
`

func (q *Queries) GetPlaces(ctx context.Context) ([]Place, error) {
	rows, err := q.db.Query(ctx, getPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Place
	for rows.Next() {
		var i Place
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
