// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: request_status_history.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const insertRequestStatusHistory = `-- name: InsertRequestStatusHistory :one
INSERT INTO request_status_history (request_id, status, comment, changed_by)
VALUES ($1, $2, $3, $4)
RETURNING id, request_id, status, comment, changed_by, changed_at
`

type InsertRequestStatusHistoryParams struct {
	RequestID uuid.UUID
	Status    RequestStatus
	Comment   *string
	ChangedBy *uuid.UUID
}

func (q *Queries) InsertRequestStatusHistory(ctx context.Context, arg InsertRequestStatusHistoryParams) (RequestStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertRequestStatusHistory,
		arg.RequestID,
		arg.Status,
		arg.Comment,
		arg.ChangedBy,
	)
	var i RequestStatusHistory
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Status,
		&i.Comment,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const listRequestStatusHistory = `-- name: ListRequestStatusHistory :many
SELECT id, request_id, status, comment, changed_by, changed_at
FROM request_status_history
WHERE request_id = $1
ORDER BY changed_at DESC
`

func (q *Queries) ListRequestStatusHistory(ctx context.Context, requestID uuid.UUID) ([]RequestStatusHistory, error) {
	rows, err := q.db.Query(ctx, listRequestStatusHistory, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestStatusHistory
	for rows.Next() {
		var i RequestStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Status,
			&i.Comment,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
