// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const assignResponsible = `-- name: AssignResponsible :one
UPDATE requests
SET responsible_user_id = $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, telegram_user_info, request_text, status, schedule_time, end_time, address, responsible_user_id, created_at, updated_at, deleted_at, created_by, updated_by
`

type AssignResponsibleParams struct {
	ID                uuid.UUID
	ResponsibleUserID *uuid.UUID
	UpdatedBy         *uuid.UUID
}

func (q *Queries) AssignResponsible(ctx context.Context, arg AssignResponsibleParams) (Request, error) {
	row := q.db.QueryRow(ctx, assignResponsible, arg.ID, arg.ResponsibleUserID, arg.UpdatedBy)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserInfo,
		&i.RequestText,
		&i.Status,
		&i.ScheduleTime,
		&i.EndTime,
		&i.Address,
		&i.ResponsibleUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, telegram_user_info, request_text, status, schedule_time, end_time, address, responsible_user_id, created_at, updated_at, deleted_at, created_by, updated_by
FROM requests
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserInfo,
		&i.RequestText,
		&i.Status,
		&i.ScheduleTime,
		&i.EndTime,
		&i.Address,
		&i.ResponsibleUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, telegram_user_info, request_text, status, schedule_time, end_time, address, responsible_user_id, created_at, updated_at, deleted_at, created_by, updated_by
FROM requests
WHERE deleted_at IS NULL
  AND responsible_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRequests(ctx context.Context, responsibleUserID *uuid.UUID) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequests, responsibleUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserInfo,
			&i.RequestText,
			&i.Status,
			&i.ScheduleTime,
			&i.EndTime,
			&i.Address,
			&i.ResponsibleUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
