// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests_equipment.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const listEquipmentForRequest = `-- name: ListEquipmentForRequest :many
SELECT request_id, equipment_id, quantity, created_at, updated_at
FROM equipment_to_requests
WHERE request_id = $1
`

func (q *Queries) ListEquipmentForRequest(ctx context.Context, requestID uuid.UUID) ([]EquipmentToRequest, error) {
	rows, err := q.db.Query(ctx, listEquipmentForRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentToRequest
	for rows.Next() {
		var i EquipmentToRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.EquipmentID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
