version: "2"
run:
  go: "1.25"
  tests: false
linters:
  enable:
    - gocyclo
    - misspell
    - revive
  disable:
    - depguard
    - dupl
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    revive:
      severity: warning
      rules:
        - name: blank-imports
        - name: indent-error-flow
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: var-naming
        - name: unused-parameter
        - name: redefines-builtin-id
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - vendor$
      - diagrams$
      - migrations$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
    - swaggo
    - gci
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - gateway
        - requests
        - auth
        - broker
        - config
        - technoBro
    gci:
      sections:
        - standard # встроенные пакеты
        - default # внешние пакеты
        - prefix(gateway) # внутренние пакеты
        - prefix(requests) # внутренние пакеты
        - prefix(auth) # внутренние пакеты
        - prefix(broker) # внутренние пакеты
        - prefix(config) # внутренние пакеты
        - prefix(utills) # внутренние пакеты
      skip-generated: true
      custom-order: true


  exclusions:
    generated: strict
    paths:
      - vendor$
      - diagrams$
      - migrations$
      - third_party$
      - builtin$
      - examples$
