// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package queries

import (
	"context"
)

const AddCategory = `-- name: AddCategory :one
insert into categories(name) values($1) returning id
`

func (q *Queries) AddCategory(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, AddCategory, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const DeleteCategory = `-- name: DeleteCategory :exec
delete from categories where id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteCategory, id)
	return err
}

const GetAllCategories = `-- name: GetAllCategories :many
select id, name, description, created_at, updated_at from categories
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, GetAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTechnicByCategory = `-- name: GetTechnicByCategory :many
select id, category_id, name, description, additional_characteristics, created_at, updated_at from equipment where category_id = $1
`

func (q *Queries) GetTechnicByCategory(ctx context.Context, categoryID *int32) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, GetTechnicByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.AdditionalCharacteristics,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateCategoryName = `-- name: UpdateCategoryName :exec
update categories set name = $1 where id = $2
`

type UpdateCategoryNameParams struct {
	Name string
	ID   int32
}

func (q *Queries) UpdateCategoryName(ctx context.Context, arg UpdateCategoryNameParams) error {
	_, err := q.db.Exec(ctx, UpdateCategoryName, arg.Name, arg.ID)
	return err
}
