// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   uuid.UUID
	Name string
}

type Technic struct {
	ID                        uuid.UUID
	CategoryID                pgtype.UUID
	Name                      string
	Description               *string
	AdditionalCharacteristics []byte
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}
