// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package queries

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson60c38f41DecodeTechInternalPostgresQueries(in *jlexer.Lexer, out *AdditionalCharacteristics) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Chars":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Chars = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.Chars)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson60c38f41EncodeTechInternalPostgresQueries(out *jwriter.Writer, in AdditionalCharacteristics) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Chars\":"
		out.RawString(prefix[1:])
		if in.Chars == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Chars {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdditionalCharacteristics) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson60c38f41EncodeTechInternalPostgresQueries(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdditionalCharacteristics) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson60c38f41EncodeTechInternalPostgresQueries(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdditionalCharacteristics) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson60c38f41DecodeTechInternalPostgresQueries(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdditionalCharacteristics) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson60c38f41DecodeTechInternalPostgresQueries(l, v)
}
