// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech.sql

package queries

import (
	"context"
)

const AddEquipment = `-- name: AddEquipment :one
insert into equipment(category_id, name, description, additional_characteristics) values($1, $2, $3, $4) returning id
`

type AddEquipmentParams struct {
	CategoryID                *int32
	Name                      string
	Description               *string
	AdditionalCharacteristics []byte
}

func (q *Queries) AddEquipment(ctx context.Context, arg AddEquipmentParams) (int32, error) {
	row := q.db.QueryRow(ctx, AddEquipment,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.AdditionalCharacteristics,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const DeleteEquipment = `-- name: DeleteEquipment :exec
delete from equipment where id = $1
`

func (q *Queries) DeleteEquipment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteEquipment, id)
	return err
}

const GetEquipmentByID = `-- name: GetEquipmentByID :one
select id, category_id, name, description, additional_characteristics, created_at, updated_at from equipment where id = $1
`

func (q *Queries) GetEquipmentByID(ctx context.Context, id int32) (Equipment, error) {
	row := q.db.QueryRow(ctx, GetEquipmentByID, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.AdditionalCharacteristics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateEquipment = `-- name: UpdateEquipment :exec
update equipment set category_id = $1, name = $2, description = $3, additional_characteristics = $4 where id = $5
`

type UpdateEquipmentParams struct {
	CategoryID                *int32
	Name                      string
	Description               *string
	AdditionalCharacteristics []byte
	ID                        int32
}

func (q *Queries) UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) error {
	_, err := q.db.Exec(ctx, UpdateEquipment,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.AdditionalCharacteristics,
		arg.ID,
	)
	return err
}
