// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const AddTechnic = `-- name: AddTechnic :one
insert into technics(category_id, name, description, additional_characteristics) values($1, $2, $3, $4) returning id
`

type AddTechnicParams struct {
	CategoryID                pgtype.UUID
	Name                      string
	Description               *string
	AdditionalCharacteristics []byte
}

func (q *Queries) AddTechnic(ctx context.Context, arg AddTechnicParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, AddTechnic,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.AdditionalCharacteristics,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const DeleteTechnic = `-- name: DeleteTechnic :exec
delete from technics where id = $1
`

func (q *Queries) DeleteTechnic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteTechnic, id)
	return err
}

const GetTechnicByID = `-- name: GetTechnicByID :one
select id, category_id, name, description, additional_characteristics, created_at, updated_at from technics where id = $1
`

func (q *Queries) GetTechnicByID(ctx context.Context, id uuid.UUID) (Technic, error) {
	row := q.db.QueryRow(ctx, GetTechnicByID, id)
	var i Technic
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.AdditionalCharacteristics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateTechnic = `-- name: UpdateTechnic :exec
update technics set category_id = $1, name = $2, description = $3, additional_characteristics = $4 where id = $5
`

type UpdateTechnicParams struct {
	CategoryID                pgtype.UUID
	Name                      string
	Description               *string
	AdditionalCharacteristics []byte
	ID                        uuid.UUID
}

func (q *Queries) UpdateTechnic(ctx context.Context, arg UpdateTechnicParams) error {
	_, err := q.db.Exec(ctx, UpdateTechnic,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.AdditionalCharacteristics,
		arg.ID,
	)
	return err
}
