// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment.sql

package queries

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const DeleteEquipmentByID = `-- name: DeleteEquipmentByID :exec
DELETE FROM equipment WHERE id = $1
`

func (q *Queries) DeleteEquipmentByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteEquipmentByID, id)
	return err
}

const GetEquipmentByRequestID = `-- name: GetEquipmentByRequestID :many
SELECT t.id, t.name, t.description, tr.quantity, t.created_at, t.updated_at
FROM equipment_to_requests tr
JOIN equipment t ON tr.equipment_id = t.id
WHERE tr.request_id = $1
ORDER BY t.created_at DESC
`

type GetEquipmentByRequestIDRow struct {
	ID          int32
	Name        string
	Description *string
	Quantity    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetEquipmentByRequestID(ctx context.Context, requestID uuid.UUID) ([]GetEquipmentByRequestIDRow, error) {
	rows, err := q.db.Query(ctx, GetEquipmentByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEquipmentByRequestIDRow
	for rows.Next() {
		var i GetEquipmentByRequestIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertEquipment = `-- name: UpsertEquipment :exec
INSERT INTO equipment (id, name, description, quantity, reserved_quantity)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET name              = EXCLUDED.name,
        description       = EXCLUDED.description,
        quantity          = EXCLUDED.quantity,
        reserved_quantity = EXCLUDED.reserved_quantity,
        updated_at        = CURRENT_TIMESTAMP
`

type UpsertEquipmentParams struct {
	ID               int32
	Name             string
	Description      *string
	Quantity         int32
	ReservedQuantity int32
}

func (q *Queries) UpsertEquipment(ctx context.Context, arg UpsertEquipmentParams) error {
	_, err := q.db.Exec(ctx, UpsertEquipment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.ReservedQuantity,
	)
	return err
}
