// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const GetEquipmentByRequestID = `-- name: GetEquipmentByRequestID :many
SELECT t.id, t.name, t.description, t.quantity, t.created_at, t.updated_at FROM equipment_to_requests tr
JOIN equipment t ON tr.equipment_id = t.id AND t.quantity > 0
WHERE tr.request_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) GetEquipmentByRequestID(ctx context.Context, requestID uuid.UUID) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, GetEquipmentByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
