// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Request struct {
	ID             uuid.UUID
	TelegramUserID uuid.UUID
	RequestText    string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Technic struct {
	ID          int32
	Name        string
	Description string
	Quantity    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TechnicsToRequest struct {
	ID        uuid.UUID
	RequestID uuid.UUID
	TechnicID int32
	Quantity  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TelegramUser struct {
	ID         uuid.UUID
	TelegramID int64
	Username   string
	FirstName  string
	LastName   *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
