// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package queries

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const AssignResponsible = `-- name: AssignResponsible :one
UPDATE requests
SET responsible_id = $2,
    status         = CASE
                         WHEN status = 'pending' THEN 'assigned'::request_status
                         ELSE status
        END,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, telegram_user_id, request_text, status, schedule_time, end_time, address, created_at, updated_at, responsible_id
`

type AssignResponsibleParams struct {
	ID            uuid.UUID
	ResponsibleID *uuid.UUID
}

func (q *Queries) AssignResponsible(ctx context.Context, arg AssignResponsibleParams) (Request, error) {
	row := q.db.QueryRow(ctx, AssignResponsible, arg.ID, arg.ResponsibleID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RequestText,
		&i.Status,
		&i.ScheduleTime,
		&i.EndTime,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponsibleID,
	)
	return i, err
}

const CreateRequest = `-- name: CreateRequest :one
INSERT INTO requests (telegram_user_id, request_text, schedule_time, address, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, telegram_user_id, request_text, status, schedule_time, end_time, address, created_at, updated_at, responsible_id
`

type CreateRequestParams struct {
	TelegramUserID uuid.UUID
	RequestText    *string
	ScheduleTime   string
	Address        string
	EndTime        time.Time
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, CreateRequest,
		arg.TelegramUserID,
		arg.RequestText,
		arg.ScheduleTime,
		arg.Address,
		arg.EndTime,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RequestText,
		&i.Status,
		&i.ScheduleTime,
		&i.EndTime,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponsibleID,
	)
	return i, err
}

const GetRequestByID = `-- name: GetRequestByID :one
SELECT id, telegram_user_id, request_text, status, schedule_time, end_time, address, created_at, updated_at, responsible_id
FROM requests
WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, GetRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RequestText,
		&i.Status,
		&i.ScheduleTime,
		&i.EndTime,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponsibleID,
	)
	return i, err
}

const GetRequests = `-- name: GetRequests :many
SELECT id, telegram_user_id, request_text, status, schedule_time, end_time, address, created_at, updated_at, responsible_id
FROM requests
ORDER BY created_at DESC
OFFSET $1 LIMIT $2
`

type GetRequestsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetRequests(ctx context.Context, arg GetRequestsParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, GetRequests, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.RequestText,
			&i.Status,
			&i.ScheduleTime,
			&i.EndTime,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponsibleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRequestsByResponsibleID = `-- name: GetRequestsByResponsibleID :many
SELECT id, telegram_user_id, request_text, status, schedule_time, end_time, address, created_at, updated_at, responsible_id
FROM requests
WHERE responsible_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRequestsByResponsibleID(ctx context.Context, responsibleID *uuid.UUID) ([]Request, error) {
	rows, err := q.db.Query(ctx, GetRequestsByResponsibleID, responsibleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.RequestText,
			&i.Status,
			&i.ScheduleTime,
			&i.EndTime,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponsibleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRequestsByTelegramUserID = `-- name: GetRequestsByTelegramUserID :many
SELECT id, telegram_user_id, request_text, status, schedule_time, end_time, address, created_at, updated_at, responsible_id
FROM requests
WHERE telegram_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetRequestsByTelegramUserIDParams struct {
	TelegramUserID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetRequestsByTelegramUserID(ctx context.Context, arg GetRequestsByTelegramUserIDParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, GetRequestsByTelegramUserID, arg.TelegramUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.RequestText,
			&i.Status,
			&i.ScheduleTime,
			&i.EndTime,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponsibleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRequestStatus = `-- name: UpdateRequestStatus :one
UPDATE requests
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, telegram_user_id, request_text, status, schedule_time, end_time, address, created_at, updated_at, responsible_id
`

type UpdateRequestStatusParams struct {
	ID     uuid.UUID
	Status RequestStatus
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error) {
	row := q.db.QueryRow(ctx, UpdateRequestStatus, arg.ID, arg.Status)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RequestText,
		&i.Status,
		&i.ScheduleTime,
		&i.EndTime,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponsibleID,
	)
	return i, err
}
