// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const CreateRequest = `-- name: CreateRequest :one
INSERT INTO requests (telegram_user_id, request_text)
VALUES ($1, $2)
RETURNING id, telegram_user_id, request_text, status, created_at, updated_at
`

type CreateRequestParams struct {
	TelegramUserID uuid.UUID
	RequestText    string
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, CreateRequest, arg.TelegramUserID, arg.RequestText)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RequestText,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRequestByID = `-- name: GetRequestByID :one
SELECT id, telegram_user_id, request_text, status, created_at, updated_at
FROM requests
WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, GetRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RequestText,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRequestsByTelegramUserID = `-- name: GetRequestsByTelegramUserID :many
SELECT id, telegram_user_id, request_text, status, created_at, updated_at
FROM requests
WHERE telegram_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetRequestsByTelegramUserIDParams struct {
	TelegramUserID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) GetRequestsByTelegramUserID(ctx context.Context, arg GetRequestsByTelegramUserIDParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, GetRequestsByTelegramUserID, arg.TelegramUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.RequestText,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRequestStatus = `-- name: UpdateRequestStatus :one
UPDATE requests
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, telegram_user_id, request_text, status, created_at, updated_at
`

type UpdateRequestStatusParams struct {
	ID     uuid.UUID
	Status RequestStatus
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error) {
	row := q.db.QueryRow(ctx, UpdateRequestStatus, arg.ID, arg.Status)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.RequestText,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
