// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: technics.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const GetTechnicsByRequestID = `-- name: GetTechnicsByRequestID :many
SELECT t.id, t.name, t.description, t.quantity, t.created_at, t.updated_at FROM technics_to_requests tr
JOIN technics t ON tr.technic_id = t.id AND t.quantity > 0
WHERE tr.request_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) GetTechnicsByRequestID(ctx context.Context, requestID uuid.UUID) ([]Technic, error) {
	rows, err := q.db.Query(ctx, GetTechnicsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Technic
	for rows.Next() {
		var i Technic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
