// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto(in *jlexer.Lexer, out *UUIDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto(out *jwriter.Writer, in UUIDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UUIDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UUIDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UUIDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UUIDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto1(in *jlexer.Lexer, out *SoftDeleteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int32(in.Int32())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
				out.UserID = nil
			} else {
				if out.UserID == nil {
					out.UserID = new(uuid.UUID)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.UnsafeBytes(); in.Ok() {
						in.AddError((*out.UserID).UnmarshalText(data))
					}
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto1(out *jwriter.Writer, in SoftDeleteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.ID))
	}
	if in.UserID != nil {
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.RawText((*in.UserID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SoftDeleteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SoftDeleteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SoftDeleteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SoftDeleteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto1(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto2(in *jlexer.Lexer, out *RoleIDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RoleID = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto2(out *jwriter.Writer, in RoleIDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role_id\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.RoleID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RoleIDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RoleIDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RoleIDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RoleIDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto2(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto3(in *jlexer.Lexer, out *RequestStatusUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.RequestID).UnmarshalText(data))
				}
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto3(out *jwriter.Writer, in RequestStatusUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.RequestID).MarshalText())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestStatusUpdateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestStatusUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestStatusUpdateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestStatusUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto3(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto4(in *jlexer.Lexer, out *RequestListByTelegramRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "telegram_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TelegramID = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int32(in.Int32())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto4(out *jwriter.Writer, in RequestListByTelegramRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"telegram_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.TelegramID))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int32(int32(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int32(int32(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestListByTelegramRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestListByTelegramRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestListByTelegramRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestListByTelegramRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto4(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto5(in *jlexer.Lexer, out *RequestIDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.RequestID).UnmarshalText(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto5(out *jwriter.Writer, in RequestIDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.RequestID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestIDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestIDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestIDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestIDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto5(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto6(in *jlexer.Lexer, out *RequestCreateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
				out.Text = nil
			} else {
				if out.Text == nil {
					out.Text = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Text = string(in.String())
				}
			}
		case "schedule_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScheduleTime = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TelegramUserID = int64(in.Int64())
			}
		case "user_name":
			if in.IsNull() {
				in.Skip()
				out.Username = nil
			} else {
				if out.Username == nil {
					out.Username = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Username = string(in.String())
				}
			}
		case "equipments":
			if in.IsNull() {
				in.Skip()
				out.Equipments = nil
			} else {
				in.Delim('[')
				if out.Equipments == nil {
					if !in.IsDelim(']') {
						out.Equipments = make([]EquipmentInfo, 0, 4)
					} else {
						out.Equipments = []EquipmentInfo{}
					}
				} else {
					out.Equipments = (out.Equipments)[:0]
				}
				for !in.IsDelim(']') {
					var v1 EquipmentInfo
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Equipments = append(out.Equipments, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "equipment_string":
			if in.IsNull() {
				in.Skip()
				out.EquipmentString = nil
			} else {
				if out.EquipmentString == nil {
					out.EquipmentString = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.EquipmentString = string(in.String())
				}
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto6(out *jwriter.Writer, in RequestCreateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Text != nil {
		const prefix string = ",\"text\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Text))
	}
	{
		const prefix string = ",\"schedule_time\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ScheduleTime))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.TelegramUserID))
	}
	if in.Username != nil {
		const prefix string = ",\"user_name\":"
		out.RawString(prefix)
		out.String(string(*in.Username))
	}
	if len(in.Equipments) != 0 {
		const prefix string = ",\"equipments\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v2, v3 := range in.Equipments {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.EquipmentString != nil {
		const prefix string = ",\"equipment_string\":"
		out.RawString(prefix)
		out.String(string(*in.EquipmentString))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestCreateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestCreateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestCreateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestCreateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto6(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto7(in *jlexer.Lexer, out *IDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto7(out *jwriter.Writer, in IDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto7(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto8(in *jlexer.Lexer, out *EquipmentItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "quantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Quantity = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto8(out *jwriter.Writer, in EquipmentItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"quantity\":"
		out.RawString(prefix)
		out.Int(int(in.Quantity))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EquipmentItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EquipmentItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EquipmentItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EquipmentItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto8(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto9(in *jlexer.Lexer, out *EquipmentInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "quantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Quantity = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto9(out *jwriter.Writer, in EquipmentInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"quantity\":"
		out.RawString(prefix)
		out.Int(int(in.Quantity))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EquipmentInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EquipmentInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EquipmentInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EquipmentInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto9(l, v)
}
func easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto10(in *jlexer.Lexer, out *EquipmentAddRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "equipments":
			if in.IsNull() {
				in.Skip()
				out.Equipments = nil
			} else {
				in.Delim('[')
				if out.Equipments == nil {
					if !in.IsDelim(']') {
						out.Equipments = make([]EquipmentItem, 0, 2)
					} else {
						out.Equipments = []EquipmentItem{}
					}
				} else {
					out.Equipments = (out.Equipments)[:0]
				}
				for !in.IsDelim(']') {
					var v4 EquipmentItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Equipments = append(out.Equipments, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto10(out *jwriter.Writer, in EquipmentAddRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"equipments\":"
		out.RawString(prefix[1:])
		if in.Equipments == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Equipments {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EquipmentAddRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EquipmentAddRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11d1a9baEncodeGithubComArtmexbetTechnoPlannerLibsDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EquipmentAddRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EquipmentAddRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11d1a9baDecodeGithubComArtmexbetTechnoPlannerLibsDto10(l, v)
}
