// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto(in *jlexer.Lexer, out *TechEquipmentUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "additional_characteristics":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.AdditionalCharacteristics = make(map[string]string)
				} else {
					out.AdditionalCharacteristics = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.AdditionalCharacteristics)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto(out *jwriter.Writer, in TechEquipmentUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if len(in.AdditionalCharacteristics) != 0 {
		const prefix string = ",\"additional_characteristics\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.AdditionalCharacteristics {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentUpdateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentUpdateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto1(in *jlexer.Lexer, out *TechEquipmentList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(TechEquipmentList, 0, 0)
			} else {
				*out = TechEquipmentList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v3 TechEquipment
			if in.IsNull() {
				in.Skip()
			} else {
				(v3).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v3)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto1(out *jwriter.Writer, in TechEquipmentList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v4, v5 := range in {
			if v4 > 0 {
				out.RawByte(',')
			}
			(v5).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto1(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto2(in *jlexer.Lexer, out *TechEquipmentGetByIDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto2(out *jwriter.Writer, in TechEquipmentGetByIDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentGetByIDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentGetByIDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentGetByIDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentGetByIDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto2(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto3(in *jlexer.Lexer, out *TechEquipmentGetByCategoryRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto3(out *jwriter.Writer, in TechEquipmentGetByCategoryRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.CategoryID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentGetByCategoryRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentGetByCategoryRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentGetByCategoryRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentGetByCategoryRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto3(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto4(in *jlexer.Lexer, out *TechEquipmentDeleteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto4(out *jwriter.Writer, in TechEquipmentDeleteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentDeleteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentDeleteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentDeleteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentDeleteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto4(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto5(in *jlexer.Lexer, out *TechEquipmentCreateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "additional_characteristics":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.AdditionalCharacteristics = make(map[string]string)
				} else {
					out.AdditionalCharacteristics = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 string
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = string(in.String())
					}
					(out.AdditionalCharacteristics)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto5(out *jwriter.Writer, in TechEquipmentCreateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if len(in.AdditionalCharacteristics) != 0 {
		const prefix string = ",\"additional_characteristics\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v7First := true
			for v7Name, v7Value := range in.AdditionalCharacteristics {
				if v7First {
					v7First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v7Name))
				out.RawByte(':')
				out.String(string(v7Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentCreateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentCreateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentCreateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentCreateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto5(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto6(in *jlexer.Lexer, out *TechEquipmentCategoryUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto6(out *jwriter.Writer, in TechEquipmentCategoryUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentCategoryUpdateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentCategoryUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentCategoryUpdateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentCategoryUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto6(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto7(in *jlexer.Lexer, out *TechEquipmentCategoryList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(TechEquipmentCategoryList, 0, 0)
			} else {
				*out = TechEquipmentCategoryList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v8 TechEquipmentCategory
			if in.IsNull() {
				in.Skip()
			} else {
				(v8).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v8)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto7(out *jwriter.Writer, in TechEquipmentCategoryList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v9, v10 := range in {
			if v9 > 0 {
				out.RawByte(',')
			}
			(v10).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentCategoryList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentCategoryList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentCategoryList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentCategoryList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto7(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto8(in *jlexer.Lexer, out *TechEquipmentCategoryGetByIDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto8(out *jwriter.Writer, in TechEquipmentCategoryGetByIDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentCategoryGetByIDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentCategoryGetByIDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentCategoryGetByIDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentCategoryGetByIDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto8(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto9(in *jlexer.Lexer, out *TechEquipmentCategoryDeleteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto9(out *jwriter.Writer, in TechEquipmentCategoryDeleteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentCategoryDeleteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentCategoryDeleteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentCategoryDeleteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentCategoryDeleteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto9(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto10(in *jlexer.Lexer, out *TechEquipmentCategoryCreateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto10(out *jwriter.Writer, in TechEquipmentCategoryCreateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentCategoryCreateRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentCategoryCreateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentCategoryCreateRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentCategoryCreateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto10(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto11(in *jlexer.Lexer, out *TechEquipmentCategory) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "audit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Audit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto11(out *jwriter.Writer, in TechEquipmentCategory) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	{
		const prefix string = ",\"audit\":"
		out.RawString(prefix)
		(in.Audit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipmentCategory) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipmentCategory) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipmentCategory) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipmentCategory) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto11(l, v)
}
func easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto12(in *jlexer.Lexer, out *TechEquipment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "additional_characteristics":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.AdditionalCharacteristics = make(map[string]string)
				} else {
					out.AdditionalCharacteristics = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v11 string
					if in.IsNull() {
						in.Skip()
					} else {
						v11 = string(in.String())
					}
					(out.AdditionalCharacteristics)[key] = v11
					in.WantComma()
				}
				in.Delim('}')
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto12(out *jwriter.Writer, in TechEquipment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if len(in.AdditionalCharacteristics) != 0 {
		const prefix string = ",\"additional_characteristics\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v12First := true
			for v12Name, v12Value := range in.AdditionalCharacteristics {
				if v12First {
					v12First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v12Name))
				out.RawByte(':')
				out.String(string(v12Value))
			}
			out.RawByte('}')
		}
	}
	if true {
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	if true {
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TechEquipment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TechEquipment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB44abcd0EncodeGithubComArtmexbetTechnoPlannerLibsDto12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TechEquipment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TechEquipment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB44abcd0DecodeGithubComArtmexbetTechnoPlannerLibsDto12(l, v)
}
