// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/artmexbet/TechnoPlanner/services/gateway/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryStorage creates a new instance of MockCategoryStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryStorage {
	mock := &MockCategoryStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryStorage is an autogenerated mock type for the CategoryStorage type
type MockCategoryStorage struct {
	mock.Mock
}

type MockCategoryStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryStorage) EXPECT() *MockCategoryStorage_Expecter {
	return &MockCategoryStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCategoryStorage
func (_mock *MockCategoryStorage) Create(ctx context.Context, cat domain.EquipmentCategory) (domain.EquipmentCategory, error) {
	ret := _mock.Called(ctx, cat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.EquipmentCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.EquipmentCategory) (domain.EquipmentCategory, error)); ok {
		return returnFunc(ctx, cat)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.EquipmentCategory) domain.EquipmentCategory); ok {
		r0 = returnFunc(ctx, cat)
	} else {
		r0 = ret.Get(0).(domain.EquipmentCategory)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.EquipmentCategory) error); ok {
		r1 = returnFunc(ctx, cat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cat domain.EquipmentCategory
func (_e *MockCategoryStorage_Expecter) Create(ctx interface{}, cat interface{}) *MockCategoryStorage_Create_Call {
	return &MockCategoryStorage_Create_Call{Call: _e.mock.On("Create", ctx, cat)}
}

func (_c *MockCategoryStorage_Create_Call) Run(run func(ctx context.Context, cat domain.EquipmentCategory)) *MockCategoryStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.EquipmentCategory
		if args[1] != nil {
			arg1 = args[1].(domain.EquipmentCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryStorage_Create_Call) Return(equipmentCategory domain.EquipmentCategory, err error) *MockCategoryStorage_Create_Call {
	_c.Call.Return(equipmentCategory, err)
	return _c
}

func (_c *MockCategoryStorage_Create_Call) RunAndReturn(run func(ctx context.Context, cat domain.EquipmentCategory) (domain.EquipmentCategory, error)) *MockCategoryStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCategoryStorage
func (_mock *MockCategoryStorage) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCategoryStorage_Expecter) Delete(ctx interface{}, id interface{}) *MockCategoryStorage_Delete_Call {
	return &MockCategoryStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCategoryStorage_Delete_Call) Run(run func(ctx context.Context, id int)) *MockCategoryStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryStorage_Delete_Call) Return(err error) *MockCategoryStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockCategoryStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCategoryStorage
func (_mock *MockCategoryStorage) List(ctx context.Context) ([]domain.EquipmentCategory, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.EquipmentCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.EquipmentCategory, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.EquipmentCategory); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.EquipmentCategory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryStorage_Expecter) List(ctx interface{}) *MockCategoryStorage_List_Call {
	return &MockCategoryStorage_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockCategoryStorage_List_Call) Run(run func(ctx context.Context)) *MockCategoryStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryStorage_List_Call) Return(equipmentCategorys []domain.EquipmentCategory, err error) *MockCategoryStorage_List_Call {
	_c.Call.Return(equipmentCategorys, err)
	return _c
}

func (_c *MockCategoryStorage_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.EquipmentCategory, error)) *MockCategoryStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCategoryStorage
func (_mock *MockCategoryStorage) Update(ctx context.Context, cat domain.EquipmentCategory) (domain.EquipmentCategory, error) {
	ret := _mock.Called(ctx, cat)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.EquipmentCategory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.EquipmentCategory) (domain.EquipmentCategory, error)); ok {
		return returnFunc(ctx, cat)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.EquipmentCategory) domain.EquipmentCategory); ok {
		r0 = returnFunc(ctx, cat)
	} else {
		r0 = ret.Get(0).(domain.EquipmentCategory)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.EquipmentCategory) error); ok {
		r1 = returnFunc(ctx, cat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cat domain.EquipmentCategory
func (_e *MockCategoryStorage_Expecter) Update(ctx interface{}, cat interface{}) *MockCategoryStorage_Update_Call {
	return &MockCategoryStorage_Update_Call{Call: _e.mock.On("Update", ctx, cat)}
}

func (_c *MockCategoryStorage_Update_Call) Run(run func(ctx context.Context, cat domain.EquipmentCategory)) *MockCategoryStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.EquipmentCategory
		if args[1] != nil {
			arg1 = args[1].(domain.EquipmentCategory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryStorage_Update_Call) Return(equipmentCategory domain.EquipmentCategory, err error) *MockCategoryStorage_Update_Call {
	_c.Call.Return(equipmentCategory, err)
	return _c
}

func (_c *MockCategoryStorage_Update_Call) RunAndReturn(run func(ctx context.Context, cat domain.EquipmentCategory) (domain.EquipmentCategory, error)) *MockCategoryStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEquipmentStorage creates a new instance of MockEquipmentStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEquipmentStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEquipmentStorage {
	mock := &MockEquipmentStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEquipmentStorage is an autogenerated mock type for the EquipmentStorage type
type MockEquipmentStorage struct {
	mock.Mock
}

type MockEquipmentStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEquipmentStorage) EXPECT() *MockEquipmentStorage_Expecter {
	return &MockEquipmentStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEquipmentStorage
func (_mock *MockEquipmentStorage) Create(ctx context.Context, eq domain.Equipment) (domain.Equipment, error) {
	ret := _mock.Called(ctx, eq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Equipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Equipment) (domain.Equipment, error)); ok {
		return returnFunc(ctx, eq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Equipment) domain.Equipment); ok {
		r0 = returnFunc(ctx, eq)
	} else {
		r0 = ret.Get(0).(domain.Equipment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Equipment) error); ok {
		r1 = returnFunc(ctx, eq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEquipmentStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEquipmentStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - eq domain.Equipment
func (_e *MockEquipmentStorage_Expecter) Create(ctx interface{}, eq interface{}) *MockEquipmentStorage_Create_Call {
	return &MockEquipmentStorage_Create_Call{Call: _e.mock.On("Create", ctx, eq)}
}

func (_c *MockEquipmentStorage_Create_Call) Run(run func(ctx context.Context, eq domain.Equipment)) *MockEquipmentStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Equipment
		if args[1] != nil {
			arg1 = args[1].(domain.Equipment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentStorage_Create_Call) Return(equipment domain.Equipment, err error) *MockEquipmentStorage_Create_Call {
	_c.Call.Return(equipment, err)
	return _c
}

func (_c *MockEquipmentStorage_Create_Call) RunAndReturn(run func(ctx context.Context, eq domain.Equipment) (domain.Equipment, error)) *MockEquipmentStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockEquipmentStorage
func (_mock *MockEquipmentStorage) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEquipmentStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEquipmentStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockEquipmentStorage_Expecter) Delete(ctx interface{}, id interface{}) *MockEquipmentStorage_Delete_Call {
	return &MockEquipmentStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEquipmentStorage_Delete_Call) Run(run func(ctx context.Context, id int)) *MockEquipmentStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentStorage_Delete_Call) Return(err error) *MockEquipmentStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEquipmentStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockEquipmentStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockEquipmentStorage
func (_mock *MockEquipmentStorage) Get(ctx context.Context, id int) (domain.Equipment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Equipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Equipment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Equipment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Equipment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEquipmentStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEquipmentStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockEquipmentStorage_Expecter) Get(ctx interface{}, id interface{}) *MockEquipmentStorage_Get_Call {
	return &MockEquipmentStorage_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockEquipmentStorage_Get_Call) Run(run func(ctx context.Context, id int)) *MockEquipmentStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentStorage_Get_Call) Return(equipment domain.Equipment, err error) *MockEquipmentStorage_Get_Call {
	_c.Call.Return(equipment, err)
	return _c
}

func (_c *MockEquipmentStorage_Get_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.Equipment, error)) *MockEquipmentStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEquipmentStorage
func (_mock *MockEquipmentStorage) List(ctx context.Context) ([]domain.Equipment, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Equipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Equipment, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Equipment); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Equipment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEquipmentStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEquipmentStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEquipmentStorage_Expecter) List(ctx interface{}) *MockEquipmentStorage_List_Call {
	return &MockEquipmentStorage_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockEquipmentStorage_List_Call) Run(run func(ctx context.Context)) *MockEquipmentStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEquipmentStorage_List_Call) Return(equipments []domain.Equipment, err error) *MockEquipmentStorage_List_Call {
	_c.Call.Return(equipments, err)
	return _c
}

func (_c *MockEquipmentStorage_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Equipment, error)) *MockEquipmentStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockEquipmentStorage
func (_mock *MockEquipmentStorage) Update(ctx context.Context, eq domain.Equipment) (domain.Equipment, error) {
	ret := _mock.Called(ctx, eq)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Equipment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Equipment) (domain.Equipment, error)); ok {
		return returnFunc(ctx, eq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Equipment) domain.Equipment); ok {
		r0 = returnFunc(ctx, eq)
	} else {
		r0 = ret.Get(0).(domain.Equipment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Equipment) error); ok {
		r1 = returnFunc(ctx, eq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEquipmentStorage_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockEquipmentStorage_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - eq domain.Equipment
func (_e *MockEquipmentStorage_Expecter) Update(ctx interface{}, eq interface{}) *MockEquipmentStorage_Update_Call {
	return &MockEquipmentStorage_Update_Call{Call: _e.mock.On("Update", ctx, eq)}
}

func (_c *MockEquipmentStorage_Update_Call) Run(run func(ctx context.Context, eq domain.Equipment)) *MockEquipmentStorage_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Equipment
		if args[1] != nil {
			arg1 = args[1].(domain.Equipment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEquipmentStorage_Update_Call) Return(equipment domain.Equipment, err error) *MockEquipmentStorage_Update_Call {
	_c.Call.Return(equipment, err)
	return _c
}

func (_c *MockEquipmentStorage_Update_Call) RunAndReturn(run func(ctx context.Context, eq domain.Equipment) (domain.Equipment, error)) *MockEquipmentStorage_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPorterStorage creates a new instance of MockPorterStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPorterStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPorterStorage {
	mock := &MockPorterStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPorterStorage is an autogenerated mock type for the PorterStorage type
type MockPorterStorage struct {
	mock.Mock
}

type MockPorterStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPorterStorage) EXPECT() *MockPorterStorage_Expecter {
	return &MockPorterStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPorterStorage
func (_mock *MockPorterStorage) Get(ctx context.Context, id uuid.UUID) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPorterStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPorterStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPorterStorage_Expecter) Get(ctx interface{}, id interface{}) *MockPorterStorage_Get_Call {
	return &MockPorterStorage_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockPorterStorage_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPorterStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPorterStorage_Get_Call) Return(user domain.User, err error) *MockPorterStorage_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockPorterStorage_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.User, error)) *MockPorterStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPorterStorage
func (_mock *MockPorterStorage) List(ctx context.Context, roleID int32) ([]domain.User, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]domain.User, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []domain.User); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPorterStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPorterStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID int32
func (_e *MockPorterStorage_Expecter) List(ctx interface{}, roleID interface{}) *MockPorterStorage_List_Call {
	return &MockPorterStorage_List_Call{Call: _e.mock.On("List", ctx, roleID)}
}

func (_c *MockPorterStorage_List_Call) Run(run func(ctx context.Context, roleID int32)) *MockPorterStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPorterStorage_List_Call) Return(users []domain.User, err error) *MockPorterStorage_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockPorterStorage_List_Call) RunAndReturn(run func(ctx context.Context, roleID int32) ([]domain.User, error)) *MockPorterStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceConnector creates a new instance of MockAuthServiceConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceConnector {
	mock := &MockAuthServiceConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthServiceConnector is an autogenerated mock type for the AuthServiceConnector type
type MockAuthServiceConnector struct {
	mock.Mock
}

type MockAuthServiceConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceConnector) EXPECT() *MockAuthServiceConnector_Expecter {
	return &MockAuthServiceConnector_Expecter{mock: &_m.Mock}
}

// RegisterPorter provides a mock function for the type MockAuthServiceConnector
func (_mock *MockAuthServiceConnector) RegisterPorter(ctx context.Context, username string, password string, email string) (string, error) {
	ret := _mock.Called(ctx, username, password, email)

	if len(ret) == 0 {
		panic("no return value specified for RegisterPorter")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, username, password, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, username, password, email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, password, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceConnector_RegisterPorter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPorter'
type MockAuthServiceConnector_RegisterPorter_Call struct {
	*mock.Call
}

// RegisterPorter is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - email string
func (_e *MockAuthServiceConnector_Expecter) RegisterPorter(ctx interface{}, username interface{}, password interface{}, email interface{}) *MockAuthServiceConnector_RegisterPorter_Call {
	return &MockAuthServiceConnector_RegisterPorter_Call{Call: _e.mock.On("RegisterPorter", ctx, username, password, email)}
}

func (_c *MockAuthServiceConnector_RegisterPorter_Call) Run(run func(ctx context.Context, username string, password string, email string)) *MockAuthServiceConnector_RegisterPorter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthServiceConnector_RegisterPorter_Call) Return(s string, err error) *MockAuthServiceConnector_RegisterPorter_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthServiceConnector_RegisterPorter_Call) RunAndReturn(run func(ctx context.Context, username string, password string, email string) (string, error)) *MockAuthServiceConnector_RegisterPorter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestHistoryStorage creates a new instance of MockRequestHistoryStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestHistoryStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestHistoryStorage {
	mock := &MockRequestHistoryStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestHistoryStorage is an autogenerated mock type for the RequestHistoryStorage type
type MockRequestHistoryStorage struct {
	mock.Mock
}

type MockRequestHistoryStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestHistoryStorage) EXPECT() *MockRequestHistoryStorage_Expecter {
	return &MockRequestHistoryStorage_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockRequestHistoryStorage
func (_mock *MockRequestHistoryStorage) Add(ctx context.Context, entry domain.RequestStatusHistory) (domain.RequestStatusHistory, error) {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 domain.RequestStatusHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RequestStatusHistory) (domain.RequestStatusHistory, error)); ok {
		return returnFunc(ctx, entry)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RequestStatusHistory) domain.RequestStatusHistory); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Get(0).(domain.RequestStatusHistory)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RequestStatusHistory) error); ok {
		r1 = returnFunc(ctx, entry)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestHistoryStorage_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockRequestHistoryStorage_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - entry domain.RequestStatusHistory
func (_e *MockRequestHistoryStorage_Expecter) Add(ctx interface{}, entry interface{}) *MockRequestHistoryStorage_Add_Call {
	return &MockRequestHistoryStorage_Add_Call{Call: _e.mock.On("Add", ctx, entry)}
}

func (_c *MockRequestHistoryStorage_Add_Call) Run(run func(ctx context.Context, entry domain.RequestStatusHistory)) *MockRequestHistoryStorage_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RequestStatusHistory
		if args[1] != nil {
			arg1 = args[1].(domain.RequestStatusHistory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestHistoryStorage_Add_Call) Return(requestStatusHistory domain.RequestStatusHistory, err error) *MockRequestHistoryStorage_Add_Call {
	_c.Call.Return(requestStatusHistory, err)
	return _c
}

func (_c *MockRequestHistoryStorage_Add_Call) RunAndReturn(run func(ctx context.Context, entry domain.RequestStatusHistory) (domain.RequestStatusHistory, error)) *MockRequestHistoryStorage_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRequestHistoryStorage
func (_mock *MockRequestHistoryStorage) List(ctx context.Context, requestID uuid.UUID) ([]domain.RequestStatusHistory, error) {
	ret := _mock.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.RequestStatusHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.RequestStatusHistory, error)); ok {
		return returnFunc(ctx, requestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.RequestStatusHistory); ok {
		r0 = returnFunc(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RequestStatusHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestHistoryStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRequestHistoryStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockRequestHistoryStorage_Expecter) List(ctx interface{}, requestID interface{}) *MockRequestHistoryStorage_List_Call {
	return &MockRequestHistoryStorage_List_Call{Call: _e.mock.On("List", ctx, requestID)}
}

func (_c *MockRequestHistoryStorage_List_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockRequestHistoryStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestHistoryStorage_List_Call) Return(requestStatusHistorys []domain.RequestStatusHistory, err error) *MockRequestHistoryStorage_List_Call {
	_c.Call.Return(requestStatusHistorys, err)
	return _c
}

func (_c *MockRequestHistoryStorage_List_Call) RunAndReturn(run func(ctx context.Context, requestID uuid.UUID) ([]domain.RequestStatusHistory, error)) *MockRequestHistoryStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestStorage creates a new instance of MockRequestStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestStorage {
	mock := &MockRequestStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestStorage is an autogenerated mock type for the RequestStorage type
type MockRequestStorage struct {
	mock.Mock
}

type MockRequestStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestStorage) EXPECT() *MockRequestStorage_Expecter {
	return &MockRequestStorage_Expecter{mock: &_m.Mock}
}

// AssignResponsible provides a mock function for the type MockRequestStorage
func (_mock *MockRequestStorage) AssignResponsible(ctx context.Context, requestID uuid.UUID, responsibleID *uuid.UUID, userID *uuid.UUID) (domain.Request, error) {
	ret := _mock.Called(ctx, requestID, responsibleID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignResponsible")
	}

	var r0 domain.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, *uuid.UUID) (domain.Request, error)); ok {
		return returnFunc(ctx, requestID, responsibleID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, *uuid.UUID) domain.Request); ok {
		r0 = returnFunc(ctx, requestID, responsibleID, userID)
	} else {
		r0 = ret.Get(0).(domain.Request)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, requestID, responsibleID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestStorage_AssignResponsible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignResponsible'
type MockRequestStorage_AssignResponsible_Call struct {
	*mock.Call
}

// AssignResponsible is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - responsibleID *uuid.UUID
//   - userID *uuid.UUID
func (_e *MockRequestStorage_Expecter) AssignResponsible(ctx interface{}, requestID interface{}, responsibleID interface{}, userID interface{}) *MockRequestStorage_AssignResponsible_Call {
	return &MockRequestStorage_AssignResponsible_Call{Call: _e.mock.On("AssignResponsible", ctx, requestID, responsibleID, userID)}
}

func (_c *MockRequestStorage_AssignResponsible_Call) Run(run func(ctx context.Context, requestID uuid.UUID, responsibleID *uuid.UUID, userID *uuid.UUID)) *MockRequestStorage_AssignResponsible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRequestStorage_AssignResponsible_Call) Return(request domain.Request, err error) *MockRequestStorage_AssignResponsible_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *MockRequestStorage_AssignResponsible_Call) RunAndReturn(run func(ctx context.Context, requestID uuid.UUID, responsibleID *uuid.UUID, userID *uuid.UUID) (domain.Request, error)) *MockRequestStorage_AssignResponsible_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRequestStorage
func (_mock *MockRequestStorage) Get(ctx context.Context, id uuid.UUID) (domain.Request, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Request, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Request); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Request)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRequestStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRequestStorage_Expecter) Get(ctx interface{}, id interface{}) *MockRequestStorage_Get_Call {
	return &MockRequestStorage_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockRequestStorage_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRequestStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestStorage_Get_Call) Return(request domain.Request, err error) *MockRequestStorage_Get_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *MockRequestStorage_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Request, error)) *MockRequestStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRequestStorage
func (_mock *MockRequestStorage) List(ctx context.Context, responsibleID *uuid.UUID) ([]domain.Request, error) {
	ret := _mock.Called(ctx, responsibleID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID) ([]domain.Request, error)); ok {
		return returnFunc(ctx, responsibleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID) []domain.Request); ok {
		r0 = returnFunc(ctx, responsibleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, responsibleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRequestStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - responsibleID *uuid.UUID
func (_e *MockRequestStorage_Expecter) List(ctx interface{}, responsibleID interface{}) *MockRequestStorage_List_Call {
	return &MockRequestStorage_List_Call{Call: _e.mock.On("List", ctx, responsibleID)}
}

func (_c *MockRequestStorage_List_Call) Run(run func(ctx context.Context, responsibleID *uuid.UUID)) *MockRequestStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequestStorage_List_Call) Return(requests []domain.Request, err error) *MockRequestStorage_List_Call {
	_c.Call.Return(requests, err)
	return _c
}

func (_c *MockRequestStorage_List_Call) RunAndReturn(run func(ctx context.Context, responsibleID *uuid.UUID) ([]domain.Request, error)) *MockRequestStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequest provides a mock function for the type MockRequestStorage
func (_mock *MockRequestStorage) UpdateRequest(ctx context.Context, requestID uuid.UUID, updates domain.RequestUpdate) (domain.Request, error) {
	ret := _mock.Called(ctx, requestID, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequest")
	}

	var r0 domain.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.RequestUpdate) (domain.Request, error)); ok {
		return returnFunc(ctx, requestID, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.RequestUpdate) domain.Request); ok {
		r0 = returnFunc(ctx, requestID, updates)
	} else {
		r0 = ret.Get(0).(domain.Request)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.RequestUpdate) error); ok {
		r1 = returnFunc(ctx, requestID, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequestStorage_UpdateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequest'
type MockRequestStorage_UpdateRequest_Call struct {
	*mock.Call
}

// UpdateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - updates domain.RequestUpdate
func (_e *MockRequestStorage_Expecter) UpdateRequest(ctx interface{}, requestID interface{}, updates interface{}) *MockRequestStorage_UpdateRequest_Call {
	return &MockRequestStorage_UpdateRequest_Call{Call: _e.mock.On("UpdateRequest", ctx, requestID, updates)}
}

func (_c *MockRequestStorage_UpdateRequest_Call) Run(run func(ctx context.Context, requestID uuid.UUID, updates domain.RequestUpdate)) *MockRequestStorage_UpdateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.RequestUpdate
		if args[2] != nil {
			arg2 = args[2].(domain.RequestUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRequestStorage_UpdateRequest_Call) Return(request domain.Request, err error) *MockRequestStorage_UpdateRequest_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *MockRequestStorage_UpdateRequest_Call) RunAndReturn(run func(ctx context.Context, requestID uuid.UUID, updates domain.RequestUpdate) (domain.Request, error)) *MockRequestStorage_UpdateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResponsibleStorage creates a new instance of MockResponsibleStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResponsibleStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResponsibleStorage {
	mock := &MockResponsibleStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResponsibleStorage is an autogenerated mock type for the ResponsibleStorage type
type MockResponsibleStorage struct {
	mock.Mock
}

type MockResponsibleStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResponsibleStorage) EXPECT() *MockResponsibleStorage_Expecter {
	return &MockResponsibleStorage_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockResponsibleStorage
func (_mock *MockResponsibleStorage) Create(ctx context.Context, id uuid.UUID, username string) (domain.Responsible, error) {
	ret := _mock.Called(ctx, id, username)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Responsible
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (domain.Responsible, error)); ok {
		return returnFunc(ctx, id, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) domain.Responsible); ok {
		r0 = returnFunc(ctx, id, username)
	} else {
		r0 = ret.Get(0).(domain.Responsible)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, id, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResponsibleStorage_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockResponsibleStorage_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - username string
func (_e *MockResponsibleStorage_Expecter) Create(ctx interface{}, id interface{}, username interface{}) *MockResponsibleStorage_Create_Call {
	return &MockResponsibleStorage_Create_Call{Call: _e.mock.On("Create", ctx, id, username)}
}

func (_c *MockResponsibleStorage_Create_Call) Run(run func(ctx context.Context, id uuid.UUID, username string)) *MockResponsibleStorage_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResponsibleStorage_Create_Call) Return(responsible domain.Responsible, err error) *MockResponsibleStorage_Create_Call {
	_c.Call.Return(responsible, err)
	return _c
}

func (_c *MockResponsibleStorage_Create_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, username string) (domain.Responsible, error)) *MockResponsibleStorage_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockResponsibleStorage
func (_mock *MockResponsibleStorage) List(ctx context.Context) ([]domain.Responsible, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Responsible
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Responsible, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Responsible); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Responsible)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResponsibleStorage_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockResponsibleStorage_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockResponsibleStorage_Expecter) List(ctx interface{}) *MockResponsibleStorage_List_Call {
	return &MockResponsibleStorage_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockResponsibleStorage_List_Call) Run(run func(ctx context.Context)) *MockResponsibleStorage_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponsibleStorage_List_Call) Return(responsibles []domain.Responsible, err error) *MockResponsibleStorage_List_Call {
	_c.Call.Return(responsibles, err)
	return _c
}

func (_c *MockResponsibleStorage_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Responsible, error)) *MockResponsibleStorage_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockuserStorage creates a new instance of mockuserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserStorage {
	mock := &mockuserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserStorage is an autogenerated mock type for the userStorage type
type mockuserStorage struct {
	mock.Mock
}

type mockuserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserStorage) EXPECT() *mockuserStorage_Expecter {
	return &mockuserStorage_Expecter{mock: &_m.Mock}
}
