// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const AddPlace = `-- name: AddPlace :one
INSERT INTO places (name, description, latitude, longitude)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, latitude, longitude, created_at, updated_at
`

type AddPlaceParams struct {
	Name        string
	Description pgtype.Text
	Latitude    float64
	Longitude   float64
}

func (q *Queries) AddPlace(ctx context.Context, arg AddPlaceParams) (Place, error) {
	row := q.db.QueryRow(ctx, AddPlace,
		arg.Name,
		arg.Description,
		arg.Latitude,
		arg.Longitude,
	)
	var i Place
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
