name: techno_planner_full
services:
  broker:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - tech-stage

  db:
    image: postgres:17-alpine3.22
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    env_file:
      - ".env"
    volumes:
      - indie_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tech-stage

  redis:
    image: redis:8.2.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - indie_redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tech-stage

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "5778:5778"
    networks:
      - tech-stage

#  migrator:
#    build:
#      context: ./migrator
#      dockerfile: Dockerfile
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      POSTGRES_HOST: db
#      POSTGRES_PORT: "5432"
#    volumes:
#      - ../services/auth/migrations:/migrations/auth:ro
#      - ../services/gateway/migrations:/migrations/gateway:ro
#      - ../services/requests/migrations:/migrations/requests:ro
#      - ../services/tech/migrations:/migrations/tech:ro
#    networks:
#      - tech-stage

  auth:
    build:
      context: ../
      dockerfile: ./deploy/build/Dockerfile
      args:
        service_name: auth
    environment:
      CONFIG_PATH: ./stage.yaml
    volumes:
      - ../services/auth/cmd/config/stage.yaml:/app/stage.yaml:ro
    ports:
      - "${AUTH_PORT:-8081}:8081"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      broker:
        condition: service_started
#      migrator:
#        condition: service_completed_successfully
    networks:
      - tech-stage

  gateway:
    build:
      context: ../
      dockerfile: ./deploy/build/Dockerfile
      args:
        service_name: gateway
    environment:
      CONFIG_PATH: ./stage.yaml
    volumes:
      - ../services/gateway/cmd/config/stage.yaml:/app/stage.yaml:ro
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    depends_on:
      auth:
        condition: service_started
      broker:
        condition: service_started
#      migrator:
#        condition: service_completed_successfully
    networks:
      - tech-stage

  requests:
    build:
      context: ../
      dockerfile: ./deploy/build/Dockerfile
      args:
        service_name: requests
    environment:
      CONFIG_PATH: ./stage.yaml
    volumes:
      - ../services/requests/cmd/config/stage.yaml:/app/stage.yaml:ro
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
#      migrator:
#        condition: service_completed_successfully
    networks:
      - tech-stage

#  tech:
#    build:
#      context: ../
#      dockerfile: ./deploy/build/Dockerfile
#      args:
#        service_name: tech
#        cmd_path: cmd/app/main.go
#    environment:
#      CONFIG_PATH: ./stage.yaml
#    volumes:
#      - ../services/tech/cmd/config/stage.yaml:/app/stage.yaml:ro
#    depends_on:
#      db:
#        condition: service_healthy
#      broker:
#        condition: service_started
#      migrator:
#        condition: service_completed_successfully
#    networks:
#      - tech-stage

networks:
  tech-stage:

volumes:
  indie_data:
  indie_redis_data:
