// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"auth/internal/models"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockiRedis creates a new instance of mockiRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockiRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockiRedis {
	mock := &mockiRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockiRedis is an autogenerated mock type for the iRedis type
type mockiRedis struct {
	mock.Mock
}

type mockiRedis_Expecter struct {
	mock *mock.Mock
}

func (_m *mockiRedis) EXPECT() *mockiRedis_Expecter {
	return &mockiRedis_Expecter{mock: &_m.Mock}
}

// DeleteAllUserSessions provides a mock function for the type mockiRedis
func (_mock *mockiRedis) DeleteAllUserSessions(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllUserSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockiRedis_DeleteAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllUserSessions'
type mockiRedis_DeleteAllUserSessions_Call struct {
	*mock.Call
}

// DeleteAllUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockiRedis_Expecter) DeleteAllUserSessions(ctx interface{}, userID interface{}) *mockiRedis_DeleteAllUserSessions_Call {
	return &mockiRedis_DeleteAllUserSessions_Call{Call: _e.mock.On("DeleteAllUserSessions", ctx, userID)}
}

func (_c *mockiRedis_DeleteAllUserSessions_Call) Run(run func(ctx context.Context, userID string)) *mockiRedis_DeleteAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiRedis_DeleteAllUserSessions_Call) Return(err error) *mockiRedis_DeleteAllUserSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockiRedis_DeleteAllUserSessions_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *mockiRedis_DeleteAllUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type mockiRedis
func (_mock *mockiRedis) DeleteSession(ctx context.Context, sessionID string, userID string) error {
	ret := _mock.Called(ctx, sessionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, sessionID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockiRedis_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type mockiRedis_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - userID string
func (_e *mockiRedis_Expecter) DeleteSession(ctx interface{}, sessionID interface{}, userID interface{}) *mockiRedis_DeleteSession_Call {
	return &mockiRedis_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID, userID)}
}

func (_c *mockiRedis_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string, userID string)) *mockiRedis_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockiRedis_DeleteSession_Call) Return(err error) *mockiRedis_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockiRedis_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, userID string) error) *mockiRedis_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type mockiRedis
func (_mock *mockiRedis) GetSession(ctx context.Context, refreshToken string) ([]byte, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiRedis_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type mockiRedis_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *mockiRedis_Expecter) GetSession(ctx interface{}, refreshToken interface{}) *mockiRedis_GetSession_Call {
	return &mockiRedis_GetSession_Call{Call: _e.mock.On("GetSession", ctx, refreshToken)}
}

func (_c *mockiRedis_GetSession_Call) Run(run func(ctx context.Context, refreshToken string)) *mockiRedis_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiRedis_GetSession_Call) Return(bytes []byte, err error) *mockiRedis_GetSession_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockiRedis_GetSession_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) ([]byte, error)) *mockiRedis_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSessions provides a mock function for the type mockiRedis
func (_mock *mockiRedis) GetUserSessions(ctx context.Context, userID string) ([][]byte, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSessions")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([][]byte, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [][]byte); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiRedis_GetUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSessions'
type mockiRedis_GetUserSessions_Call struct {
	*mock.Call
}

// GetUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockiRedis_Expecter) GetUserSessions(ctx interface{}, userID interface{}) *mockiRedis_GetUserSessions_Call {
	return &mockiRedis_GetUserSessions_Call{Call: _e.mock.On("GetUserSessions", ctx, userID)}
}

func (_c *mockiRedis_GetUserSessions_Call) Run(run func(ctx context.Context, userID string)) *mockiRedis_GetUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiRedis_GetUserSessions_Call) Return(bytess [][]byte, err error) *mockiRedis_GetUserSessions_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *mockiRedis_GetUserSessions_Call) RunAndReturn(run func(ctx context.Context, userID string) ([][]byte, error)) *mockiRedis_GetUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSession provides a mock function for the type mockiRedis
func (_mock *mockiRedis) StoreSession(ctx context.Context, sessionID string, userID string, refreshToken string, sessionData []byte, tokenTTL time.Duration) error {
	ret := _mock.Called(ctx, sessionID, userID, refreshToken, sessionData, tokenTTL)

	if len(ret) == 0 {
		panic("no return value specified for StoreSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, sessionID, userID, refreshToken, sessionData, tokenTTL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockiRedis_StoreSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSession'
type mockiRedis_StoreSession_Call struct {
	*mock.Call
}

// StoreSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - userID string
//   - refreshToken string
//   - sessionData []byte
//   - tokenTTL time.Duration
func (_e *mockiRedis_Expecter) StoreSession(ctx interface{}, sessionID interface{}, userID interface{}, refreshToken interface{}, sessionData interface{}, tokenTTL interface{}) *mockiRedis_StoreSession_Call {
	return &mockiRedis_StoreSession_Call{Call: _e.mock.On("StoreSession", ctx, sessionID, userID, refreshToken, sessionData, tokenTTL)}
}

func (_c *mockiRedis_StoreSession_Call) Run(run func(ctx context.Context, sessionID string, userID string, refreshToken string, sessionData []byte, tokenTTL time.Duration)) *mockiRedis_StoreSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		var arg5 time.Duration
		if args[5] != nil {
			arg5 = args[5].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockiRedis_StoreSession_Call) Return(err error) *mockiRedis_StoreSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockiRedis_StoreSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, userID string, refreshToken string, sessionData []byte, tokenTTL time.Duration) error) *mockiRedis_StoreSession_Call {
	_c.Call.Return(run)
	return _c
}

// newMockiPostgres creates a new instance of mockiPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockiPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockiPostgres {
	mock := &mockiPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockiPostgres is an autogenerated mock type for the iPostgres type
type mockiPostgres struct {
	mock.Mock
}

type mockiPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *mockiPostgres) EXPECT() *mockiPostgres_Expecter {
	return &mockiPostgres_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockiPostgres
func (_mock *mockiPostgres) CreateUser(ctx context.Context, username string, email string, passwordHash string) (models.User, error) {
	ret := _mock.Called(ctx, username, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (models.User, error)); ok {
		return returnFunc(ctx, username, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) models.User); ok {
		r0 = returnFunc(ctx, username, email, passwordHash)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiPostgres_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockiPostgres_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
//   - passwordHash string
func (_e *mockiPostgres_Expecter) CreateUser(ctx interface{}, username interface{}, email interface{}, passwordHash interface{}) *mockiPostgres_CreateUser_Call {
	return &mockiPostgres_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, email, passwordHash)}
}

func (_c *mockiPostgres_CreateUser_Call) Run(run func(ctx context.Context, username string, email string, passwordHash string)) *mockiPostgres_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockiPostgres_CreateUser_Call) Return(user models.User, err error) *mockiPostgres_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockiPostgres_CreateUser_Call) RunAndReturn(run func(ctx context.Context, username string, email string, passwordHash string) (models.User, error)) *mockiPostgres_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function for the type mockiPostgres
func (_mock *mockiPostgres) FindUserByUsername(ctx context.Context, username string) (models.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiPostgres_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type mockiPostgres_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockiPostgres_Expecter) FindUserByUsername(ctx interface{}, username interface{}) *mockiPostgres_FindUserByUsername_Call {
	return &mockiPostgres_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, username)}
}

func (_c *mockiPostgres_FindUserByUsername_Call) Run(run func(ctx context.Context, username string)) *mockiPostgres_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiPostgres_FindUserByUsername_Call) Return(user models.User, err error) *mockiPostgres_FindUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockiPostgres_FindUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (models.User, error)) *mockiPostgres_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}
