// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"auth/internal/models"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockiTokenizer creates a new instance of mockiTokenizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockiTokenizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockiTokenizer {
	mock := &mockiTokenizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockiTokenizer is an autogenerated mock type for the iTokenizer type
type mockiTokenizer struct {
	mock.Mock
}

type mockiTokenizer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockiTokenizer) EXPECT() *mockiTokenizer_Expecter {
	return &mockiTokenizer_Expecter{mock: &_m.Mock}
}

// DecodeToken provides a mock function for the type mockiTokenizer
func (_mock *mockiTokenizer) DecodeToken(ctx context.Context, tokenStr string) (*models.Claims, error) {
	ret := _mock.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for DecodeToken")
	}

	var r0 *models.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Claims, error)); ok {
		return returnFunc(ctx, tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Claims); ok {
		r0 = returnFunc(ctx, tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiTokenizer_DecodeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecodeToken'
type mockiTokenizer_DecodeToken_Call struct {
	*mock.Call
}

// DecodeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenStr string
func (_e *mockiTokenizer_Expecter) DecodeToken(ctx interface{}, tokenStr interface{}) *mockiTokenizer_DecodeToken_Call {
	return &mockiTokenizer_DecodeToken_Call{Call: _e.mock.On("DecodeToken", ctx, tokenStr)}
}

func (_c *mockiTokenizer_DecodeToken_Call) Run(run func(ctx context.Context, tokenStr string)) *mockiTokenizer_DecodeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiTokenizer_DecodeToken_Call) Return(claims *models.Claims, err error) *mockiTokenizer_DecodeToken_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *mockiTokenizer_DecodeToken_Call) RunAndReturn(run func(ctx context.Context, tokenStr string) (*models.Claims, error)) *mockiTokenizer_DecodeToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSession provides a mock function for the type mockiTokenizer
func (_mock *mockiTokenizer) GenerateSession(u models.User, deviceID string, userAgent string, ip string) *models.Session {
	ret := _mock.Called(u, deviceID, userAgent, ip)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSession")
	}

	var r0 *models.Session
	if returnFunc, ok := ret.Get(0).(func(models.User, string, string, string) *models.Session); ok {
		r0 = returnFunc(u, deviceID, userAgent, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	return r0
}

// mockiTokenizer_GenerateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSession'
type mockiTokenizer_GenerateSession_Call struct {
	*mock.Call
}

// GenerateSession is a helper method to define mock.On call
//   - u models.User
//   - deviceID string
//   - userAgent string
//   - ip string
func (_e *mockiTokenizer_Expecter) GenerateSession(u interface{}, deviceID interface{}, userAgent interface{}, ip interface{}) *mockiTokenizer_GenerateSession_Call {
	return &mockiTokenizer_GenerateSession_Call{Call: _e.mock.On("GenerateSession", u, deviceID, userAgent, ip)}
}

func (_c *mockiTokenizer_GenerateSession_Call) Run(run func(u models.User, deviceID string, userAgent string, ip string)) *mockiTokenizer_GenerateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.User
		if args[0] != nil {
			arg0 = args[0].(models.User)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockiTokenizer_GenerateSession_Call) Return(session *models.Session) *mockiTokenizer_GenerateSession_Call {
	_c.Call.Return(session)
	return _c
}

func (_c *mockiTokenizer_GenerateSession_Call) RunAndReturn(run func(u models.User, deviceID string, userAgent string, ip string) *models.Session) *mockiTokenizer_GenerateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateTokenPair provides a mock function for the type mockiTokenizer
func (_mock *mockiTokenizer) GenerateTokenPair(ctx context.Context, userid string, role string) (models.TokenPair, error) {
	ret := _mock.Called(ctx, userid, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 models.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (models.TokenPair, error)); ok {
		return returnFunc(ctx, userid, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) models.TokenPair); ok {
		r0 = returnFunc(ctx, userid, role)
	} else {
		r0 = ret.Get(0).(models.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userid, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiTokenizer_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type mockiTokenizer_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - userid string
//   - role string
func (_e *mockiTokenizer_Expecter) GenerateTokenPair(ctx interface{}, userid interface{}, role interface{}) *mockiTokenizer_GenerateTokenPair_Call {
	return &mockiTokenizer_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", ctx, userid, role)}
}

func (_c *mockiTokenizer_GenerateTokenPair_Call) Run(run func(ctx context.Context, userid string, role string)) *mockiTokenizer_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockiTokenizer_GenerateTokenPair_Call) Return(tokenPair models.TokenPair, err error) *mockiTokenizer_GenerateTokenPair_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *mockiTokenizer_GenerateTokenPair_Call) RunAndReturn(run func(ctx context.Context, userid string, role string) (models.TokenPair, error)) *mockiTokenizer_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// newMockiRepository creates a new instance of mockiRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockiRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockiRepository {
	mock := &mockiRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockiRepository is an autogenerated mock type for the iRepository type
type mockiRepository struct {
	mock.Mock
}

type mockiRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockiRepository) EXPECT() *mockiRepository_Expecter {
	return &mockiRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type mockiRepository
func (_mock *mockiRepository) CreateUser(ctx context.Context, username string, email string, passwordHash string) (models.User, error) {
	ret := _mock.Called(ctx, username, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (models.User, error)); ok {
		return returnFunc(ctx, username, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) models.User); ok {
		r0 = returnFunc(ctx, username, email, passwordHash)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type mockiRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
//   - passwordHash string
func (_e *mockiRepository_Expecter) CreateUser(ctx interface{}, username interface{}, email interface{}, passwordHash interface{}) *mockiRepository_CreateUser_Call {
	return &mockiRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, email, passwordHash)}
}

func (_c *mockiRepository_CreateUser_Call) Run(run func(ctx context.Context, username string, email string, passwordHash string)) *mockiRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockiRepository_CreateUser_Call) Return(user models.User, err error) *mockiRepository_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockiRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, username string, email string, passwordHash string) (models.User, error)) *mockiRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllUserSessions provides a mock function for the type mockiRepository
func (_mock *mockiRepository) DeleteAllUserSessions(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllUserSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockiRepository_DeleteAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllUserSessions'
type mockiRepository_DeleteAllUserSessions_Call struct {
	*mock.Call
}

// DeleteAllUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockiRepository_Expecter) DeleteAllUserSessions(ctx interface{}, userID interface{}) *mockiRepository_DeleteAllUserSessions_Call {
	return &mockiRepository_DeleteAllUserSessions_Call{Call: _e.mock.On("DeleteAllUserSessions", ctx, userID)}
}

func (_c *mockiRepository_DeleteAllUserSessions_Call) Run(run func(ctx context.Context, userID string)) *mockiRepository_DeleteAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiRepository_DeleteAllUserSessions_Call) Return(err error) *mockiRepository_DeleteAllUserSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockiRepository_DeleteAllUserSessions_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *mockiRepository_DeleteAllUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type mockiRepository
func (_mock *mockiRepository) DeleteSession(ctx context.Context, sessionID string, userID string) error {
	ret := _mock.Called(ctx, sessionID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, sessionID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockiRepository_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type mockiRepository_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - userID string
func (_e *mockiRepository_Expecter) DeleteSession(ctx interface{}, sessionID interface{}, userID interface{}) *mockiRepository_DeleteSession_Call {
	return &mockiRepository_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx, sessionID, userID)}
}

func (_c *mockiRepository_DeleteSession_Call) Run(run func(ctx context.Context, sessionID string, userID string)) *mockiRepository_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockiRepository_DeleteSession_Call) Return(err error) *mockiRepository_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockiRepository_DeleteSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, userID string) error) *mockiRepository_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshToken provides a mock function for the type mockiRepository
func (_mock *mockiRepository) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (*models.Session, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshToken")
	}

	var r0 *models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Session, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Session); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiRepository_GetSessionByRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshToken'
type mockiRepository_GetSessionByRefreshToken_Call struct {
	*mock.Call
}

// GetSessionByRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *mockiRepository_Expecter) GetSessionByRefreshToken(ctx interface{}, refreshToken interface{}) *mockiRepository_GetSessionByRefreshToken_Call {
	return &mockiRepository_GetSessionByRefreshToken_Call{Call: _e.mock.On("GetSessionByRefreshToken", ctx, refreshToken)}
}

func (_c *mockiRepository_GetSessionByRefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *mockiRepository_GetSessionByRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiRepository_GetSessionByRefreshToken_Call) Return(session *models.Session, err error) *mockiRepository_GetSessionByRefreshToken_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *mockiRepository_GetSessionByRefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*models.Session, error)) *mockiRepository_GetSessionByRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type mockiRepository
func (_mock *mockiRepository) GetUserByUsername(ctx context.Context, username string) (models.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockiRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type mockiRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *mockiRepository_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *mockiRepository_GetUserByUsername_Call {
	return &mockiRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *mockiRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *mockiRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockiRepository_GetUserByUsername_Call) Return(user models.User, err error) *mockiRepository_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockiRepository_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (models.User, error)) *mockiRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// StoreToken provides a mock function for the type mockiRepository
func (_mock *mockiRepository) StoreToken(ctx context.Context, session *models.Session, refreshToken string) error {
	ret := _mock.Called(ctx, session, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for StoreToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Session, string) error); ok {
		r0 = returnFunc(ctx, session, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockiRepository_StoreToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreToken'
type mockiRepository_StoreToken_Call struct {
	*mock.Call
}

// StoreToken is a helper method to define mock.On call
//   - ctx context.Context
//   - session *models.Session
//   - refreshToken string
func (_e *mockiRepository_Expecter) StoreToken(ctx interface{}, session interface{}, refreshToken interface{}) *mockiRepository_StoreToken_Call {
	return &mockiRepository_StoreToken_Call{Call: _e.mock.On("StoreToken", ctx, session, refreshToken)}
}

func (_c *mockiRepository_StoreToken_Call) Run(run func(ctx context.Context, session *models.Session, refreshToken string)) *mockiRepository_StoreToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Session
		if args[1] != nil {
			arg1 = args[1].(*models.Session)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockiRepository_StoreToken_Call) Return(err error) *mockiRepository_StoreToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockiRepository_StoreToken_Call) RunAndReturn(run func(ctx context.Context, session *models.Session, refreshToken string) error) *mockiRepository_StoreToken_Call {
	_c.Call.Return(run)
	return _c
}
