// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package wrapnats

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	domain "requests/internal/domain"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeRequestsInternalWrapnats(in *jlexer.Lexer, out *response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "payload":
			if m, ok := out.Payload.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Payload.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Payload = in.Interface()
			}
		case "statusCode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StatusCode = statusCode(in.Int())
			}
		case "isError":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsError = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeRequestsInternalWrapnats(out *jwriter.Writer, in response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		if m, ok := in.Payload.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Payload.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Payload))
		}
	}
	{
		const prefix string = ",\"statusCode\":"
		out.RawString(prefix)
		out.Int(int(in.StatusCode))
	}
	{
		const prefix string = ",\"isError\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsError))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeRequestsInternalWrapnats(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeRequestsInternalWrapnats(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeRequestsInternalWrapnats(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeRequestsInternalWrapnats(l, v)
}
func easyjsonD2b7633eDecodeRequestsInternalWrapnats1(in *jlexer.Lexer, out *requestUpdateStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.RequestID).UnmarshalText(data))
				}
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeRequestsInternalWrapnats1(out *jwriter.Writer, in requestUpdateStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.RequestID).MarshalText())
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v requestUpdateStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeRequestsInternalWrapnats1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v requestUpdateStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeRequestsInternalWrapnats1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *requestUpdateStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeRequestsInternalWrapnats1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *requestUpdateStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeRequestsInternalWrapnats1(l, v)
}
func easyjsonD2b7633eDecodeRequestsInternalWrapnats2(in *jlexer.Lexer, out *requestList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "telegram_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TelegramID = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int32(in.Int32())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeRequestsInternalWrapnats2(out *jwriter.Writer, in requestList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"telegram_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.TelegramID))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int32(int32(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int32(int32(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v requestList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeRequestsInternalWrapnats2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v requestList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeRequestsInternalWrapnats2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *requestList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeRequestsInternalWrapnats2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *requestList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeRequestsInternalWrapnats2(l, v)
}
func easyjsonD2b7633eDecodeRequestsInternalWrapnats3(in *jlexer.Lexer, out *requestCreate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
				out.Text = nil
			} else {
				if out.Text == nil {
					out.Text = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Text = string(in.String())
				}
			}
		case "schedule_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScheduleTime = string(in.String())
			}
		case "telegram_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TelegramID = int64(in.Int64())
			}
		case "equipments":
			if in.IsNull() {
				in.Skip()
				out.Equipments = nil
			} else {
				in.Delim('[')
				if out.Equipments == nil {
					if !in.IsDelim(']') {
						out.Equipments = make([]equipmentInfo, 0, 4)
					} else {
						out.Equipments = []equipmentInfo{}
					}
				} else {
					out.Equipments = (out.Equipments)[:0]
				}
				for !in.IsDelim(']') {
					var v1 equipmentInfo
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Equipments = append(out.Equipments, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeRequestsInternalWrapnats3(out *jwriter.Writer, in requestCreate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		if in.Text == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Text))
		}
	}
	{
		const prefix string = ",\"schedule_time\":"
		out.RawString(prefix)
		out.String(string(in.ScheduleTime))
	}
	{
		const prefix string = ",\"telegram_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.TelegramID))
	}
	{
		const prefix string = ",\"equipments\":"
		out.RawString(prefix)
		if in.Equipments == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Equipments {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v requestCreate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeRequestsInternalWrapnats3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v requestCreate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeRequestsInternalWrapnats3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *requestCreate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeRequestsInternalWrapnats3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *requestCreate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeRequestsInternalWrapnats3(l, v)
}
func easyjsonD2b7633eDecodeRequestsInternalWrapnats4(in *jlexer.Lexer, out *requestByID) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.RequestID).UnmarshalText(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeRequestsInternalWrapnats4(out *jwriter.Writer, in requestByID) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.RequestID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v requestByID) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeRequestsInternalWrapnats4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v requestByID) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeRequestsInternalWrapnats4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *requestByID) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeRequestsInternalWrapnats4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *requestByID) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeRequestsInternalWrapnats4(l, v)
}
func easyjsonD2b7633eDecodeRequestsInternalWrapnats5(in *jlexer.Lexer, out *equipmentInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int(in.Int())
			}
		case "quantity":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Quantity = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeRequestsInternalWrapnats5(out *jwriter.Writer, in equipmentInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"quantity\":"
		out.RawString(prefix)
		out.Int(int(in.Quantity))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v equipmentInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeRequestsInternalWrapnats5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v equipmentInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeRequestsInternalWrapnats5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *equipmentInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeRequestsInternalWrapnats5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *equipmentInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeRequestsInternalWrapnats5(l, v)
}
func easyjsonD2b7633eDecodeRequestsInternalWrapnats6(in *jlexer.Lexer, out *addEquipment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "equipments":
			if in.IsNull() {
				in.Skip()
				out.Equipments = nil
			} else {
				in.Delim('[')
				if out.Equipments == nil {
					if !in.IsDelim(']') {
						out.Equipments = make([]domain.Equipment, 0, 0)
					} else {
						out.Equipments = []domain.Equipment{}
					}
				} else {
					out.Equipments = (out.Equipments)[:0]
				}
				for !in.IsDelim(']') {
					var v4 domain.Equipment
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Equipments = append(out.Equipments, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeRequestsInternalWrapnats6(out *jwriter.Writer, in addEquipment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"equipments\":"
		out.RawString(prefix[1:])
		if in.Equipments == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Equipments {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v addEquipment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeRequestsInternalWrapnats6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v addEquipment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeRequestsInternalWrapnats6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *addEquipment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeRequestsInternalWrapnats6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *addEquipment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeRequestsInternalWrapnats6(l, v)
}
