// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package equipment

import (
	"context"

	"github.com/artmexbet/TechnoPlanner/services/requests/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateEquipment provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateEquipment(ctx context.Context, technics []domain.Equipment) error {
	ret := _mock.Called(ctx, technics)

	if len(ret) == 0 {
		panic("no return value specified for CreateEquipment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.Equipment) error); ok {
		r0 = returnFunc(ctx, technics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateEquipment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEquipment'
type MockRepository_CreateEquipment_Call struct {
	*mock.Call
}

// CreateEquipment is a helper method to define mock.On call
//   - ctx context.Context
//   - technics []domain.Equipment
func (_e *MockRepository_Expecter) CreateEquipment(ctx interface{}, technics interface{}) *MockRepository_CreateEquipment_Call {
	return &MockRepository_CreateEquipment_Call{Call: _e.mock.On("CreateEquipment", ctx, technics)}
}

func (_c *MockRepository_CreateEquipment_Call) Run(run func(ctx context.Context, technics []domain.Equipment)) *MockRepository_CreateEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.Equipment
		if args[1] != nil {
			arg1 = args[1].([]domain.Equipment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateEquipment_Call) Return(err error) *MockRepository_CreateEquipment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateEquipment_Call) RunAndReturn(run func(ctx context.Context, technics []domain.Equipment) error) *MockRepository_CreateEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertEquipment provides a mock function for the type MockRepository
func (_mock *MockRepository) UpsertEquipment(ctx context.Context, eq domain.Equipment) error {
	ret := _mock.Called(ctx, eq)
	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Equipment) error); ok {
		r0 = returnFunc(ctx, eq)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockRepository_UpsertEquipment_Call struct{ *mock.Call }

func (_e *MockRepository_Expecter) UpsertEquipment(ctx interface{}, eq interface{}) *MockRepository_UpsertEquipment_Call {
	return &MockRepository_UpsertEquipment_Call{Call: _e.mock.On("UpsertEquipment", ctx, eq)}
}

func (_c *MockRepository_UpsertEquipment_Call) Run(run func(ctx context.Context, eq domain.Equipment)) *MockRepository_UpsertEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Equipment))
	})
	return _c
}

func (_c *MockRepository_UpsertEquipment_Call) Return(err error) *MockRepository_UpsertEquipment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpsertEquipment_Call) RunAndReturn(run func(context.Context, domain.Equipment) error) *MockRepository_UpsertEquipment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEquipment provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteEquipment(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)
	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

type MockRepository_DeleteEquipment_Call struct{ *mock.Call }

func (_e *MockRepository_Expecter) DeleteEquipment(ctx interface{}, id interface{}) *MockRepository_DeleteEquipment_Call {
	return &MockRepository_DeleteEquipment_Call{Call: _e.mock.On("DeleteEquipment", ctx, id)}
}

func (_c *MockRepository_DeleteEquipment_Call) Run(run func(ctx context.Context, id int)) *MockRepository_DeleteEquipment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_DeleteEquipment_Call) Return(err error) *MockRepository_DeleteEquipment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteEquipment_Call) RunAndReturn(run func(context.Context, int) error) *MockRepository_DeleteEquipment_Call {
	_c.Call.Return(run)
	return _c
}
