repository:
  refresh_token_ttl: 720h # 30 days
  access_token_ttl: 1h    # 1 hour
redis:
  addr: "localhost:6379"
  password: "redis"
  db: 0
  user: "redis"
  pool_size: 10
postgres:
  host: "localhost"
  port: 5433
  user: "postgres"
  pass: "postgres"
  db_name: "auth"
  ssl_mode: "disable"
jwt_secret: "very_very_very_secret_jwt_secret"