router:
  address: 0.0.0.0
  port: 8080
broker:
  host: "broker"
  port: "4222"
postgres:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  db_name: gateway
  timeout: 5s
grpc:
  address: "localhost:8081"