router:
  address: 0.0.0.0
  port: 8080
broker:
  url: ""
  streams:
    something:
      name: SMTHING
      subjects:
        - "smthing.created"
      max_age: 24h
postgres:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  db: gateway
  timeout: 5s
grpc:
  address: "localhost:8081"