router:
  address: 0.0.0.0
  port: 8080
broker:
  host: "broker"
  port: "4222"
postgres:
  host: db
  port: 5432
  user: postgres
  password: postgres
  db_name: gateway
  timeout: 5s
trace:
  insecure: true
  endpoint: "jaeger:4318"
grpc:
  address: "auth:8081"