// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech.sql

package queries

import (
	"context"
)

const AddEquipment = `-- name: AddEquipment :one
insert into equipment(category_id, name, description, additional_characteristics, quantity)
values($1, $2, $3, $4, $5) returning id
`

type AddEquipmentParams struct {
	CategoryID                *int32
	Name                      string
	Description               *string
	AdditionalCharacteristics []byte
	Quantity                  int32
}

func (q *Queries) AddEquipment(ctx context.Context, arg AddEquipmentParams) (int32, error) {
	row := q.db.QueryRow(ctx, AddEquipment,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.AdditionalCharacteristics,
		arg.Quantity,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const DeleteEquipment = `-- name: DeleteEquipment :exec
delete from equipment where id = $1
`

func (q *Queries) DeleteEquipment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteEquipment, id)
	return err
}

const GetAllEquipment = `-- name: GetAllEquipment :many
select id, category_id, name, description, additional_characteristics, created_at, updated_at, quantity, reserved_quantity from equipment order by id
`

func (q *Queries) GetAllEquipment(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, GetAllEquipment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.AdditionalCharacteristics,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Quantity,
			&i.ReservedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAvailableQuantity = `-- name: GetAvailableQuantity :one
SELECT quantity - reserved_quantity AS available FROM equipment WHERE id = $1
`

func (q *Queries) GetAvailableQuantity(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, GetAvailableQuantity, id)
	var available int32
	err := row.Scan(&available)
	return available, err
}

const GetEquipmentByID = `-- name: GetEquipmentByID :one
select id, category_id, name, description, additional_characteristics, created_at, updated_at, quantity, reserved_quantity from equipment where id = $1
`

func (q *Queries) GetEquipmentByID(ctx context.Context, id int32) (Equipment, error) {
	row := q.db.QueryRow(ctx, GetEquipmentByID, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.AdditionalCharacteristics,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
		&i.ReservedQuantity,
	)
	return i, err
}

const ReleaseEquipment = `-- name: ReleaseEquipment :exec
UPDATE equipment
SET reserved_quantity = reserved_quantity - $2
WHERE id = $1 AND reserved_quantity >= $2
`

type ReleaseEquipmentParams struct {
	ID               int32
	ReservedQuantity int32
}

func (q *Queries) ReleaseEquipment(ctx context.Context, arg ReleaseEquipmentParams) error {
	_, err := q.db.Exec(ctx, ReleaseEquipment, arg.ID, arg.ReservedQuantity)
	return err
}

const ReserveEquipment = `-- name: ReserveEquipment :exec
UPDATE equipment
SET reserved_quantity = reserved_quantity + $2
WHERE id = $1 AND (quantity - reserved_quantity) >= $2
`

type ReserveEquipmentParams struct {
	ID               int32
	ReservedQuantity int32
}

func (q *Queries) ReserveEquipment(ctx context.Context, arg ReserveEquipmentParams) error {
	_, err := q.db.Exec(ctx, ReserveEquipment, arg.ID, arg.ReservedQuantity)
	return err
}

const UpdateEquipment = `-- name: UpdateEquipment :exec
update equipment set category_id = $1, name = $2, description = $3, additional_characteristics = $4, quantity = $5 where id = $6
`

type UpdateEquipmentParams struct {
	CategoryID                *int32
	Name                      string
	Description               *string
	AdditionalCharacteristics []byte
	Quantity                  int32
	ID                        int32
}

func (q *Queries) UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) error {
	_, err := q.db.Exec(ctx, UpdateEquipment,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.AdditionalCharacteristics,
		arg.Quantity,
		arg.ID,
	)
	return err
}
