@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' Диаграмма компонентов для API Gateway
LAYOUT_TOP_DOWN()
title API Gateway - Компоненты

Container(apiGateway, "API Gateway", "Go", "Обрабатывает запросы от клиентов")

Component(authenticator, "Аутентификатор", "Go", "Управляет аутентификацией пользователей")
Component(requestRouter, "Маршрутизатор запросов", "Go", "Маршрутизирует запросы к соответствующим сервисам")
Component(rateLimiter, "Ограничитель скорости", "Go", "Ограничивает количество запросов от клиентов")
Component(apiLogger, "Логгер API", "Go", "Логирует все входящие и исходящие запросы")

Rel(authenticator, requestRouter, "Проверяет аутентификацию")
Rel(requestRouter, serviceTechManagement, "Маршрутизирует запросы о технике")
Rel(requestRouter, serviceTaskManagement, "Маршрутизирует запросы о задачах")
Rel(rateLimiter, requestRouter, "Ограничивает запросы")
Rel(apiLogger, requestRouter, "Логирует запросы")

@enduml