// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package request

import (
	"context"

	"github.com/artmexbet/TechnoPlanner/services/requests/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateRequest provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateRequest(ctx context.Context, req domain.Request) (*domain.Request, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 *domain.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Request) (*domain.Request, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Request) *domain.Request); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type MockRepository_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.Request
func (_e *MockRepository_Expecter) CreateRequest(ctx interface{}, req interface{}) *MockRepository_CreateRequest_Call {
	return &MockRepository_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, req)}
}

func (_c *MockRepository_CreateRequest_Call) Run(run func(ctx context.Context, req domain.Request)) *MockRepository_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Request
		if args[1] != nil {
			arg1 = args[1].(domain.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateRequest_Call) Return(request *domain.Request, err error) *MockRepository_CreateRequest_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *MockRepository_CreateRequest_Call) RunAndReturn(run func(ctx context.Context, req domain.Request) (*domain.Request, error)) *MockRepository_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetRequestByID(ctx context.Context, requestID uuid.UUID) (*domain.Request, error) {
	ret := _mock.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestByID")
	}

	var r0 *domain.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Request, error)); ok {
		return returnFunc(ctx, requestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Request); ok {
		r0 = returnFunc(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetRequestByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestByID'
type MockRepository_GetRequestByID_Call struct {
	*mock.Call
}

// GetRequestByID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
func (_e *MockRepository_Expecter) GetRequestByID(ctx interface{}, requestID interface{}) *MockRepository_GetRequestByID_Call {
	return &MockRepository_GetRequestByID_Call{Call: _e.mock.On("GetRequestByID", ctx, requestID)}
}

func (_c *MockRepository_GetRequestByID_Call) Run(run func(ctx context.Context, requestID uuid.UUID)) *MockRepository_GetRequestByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetRequestByID_Call) Return(request *domain.Request, err error) *MockRepository_GetRequestByID_Call {
	_c.Call.Return(request, err)
	return _c
}

func (_c *MockRepository_GetRequestByID_Call) RunAndReturn(run func(ctx context.Context, requestID uuid.UUID) (*domain.Request, error)) *MockRepository_GetRequestByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestsByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetRequestsByUserID(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]domain.Request, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestsByUserID")
	}

	var r0 []domain.Request
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) ([]domain.Request, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, int32) []domain.Request); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, int32) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetRequestsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestsByUserID'
type MockRepository_GetRequestsByUserID_Call struct {
	*mock.Call
}

// GetRequestsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int32
//   - offset int32
func (_e *MockRepository_Expecter) GetRequestsByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockRepository_GetRequestsByUserID_Call {
	return &MockRepository_GetRequestsByUserID_Call{Call: _e.mock.On("GetRequestsByUserID", ctx, userID, limit, offset)}
}

func (_c *MockRepository_GetRequestsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32)) *MockRepository_GetRequestsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_GetRequestsByUserID_Call) Return(requests []domain.Request, err error) *MockRepository_GetRequestsByUserID_Call {
	_c.Call.Return(requests, err)
	return _c
}

func (_c *MockRepository_GetRequestsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int32, offset int32) ([]domain.Request, error)) *MockRepository_GetRequestsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTelegramUser provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveTelegramUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveTelegramUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SaveTelegramUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTelegramUser'
type MockRepository_SaveTelegramUser_Call struct {
	*mock.Call
}

// SaveTelegramUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockRepository_Expecter) SaveTelegramUser(ctx interface{}, user interface{}) *MockRepository_SaveTelegramUser_Call {
	return &MockRepository_SaveTelegramUser_Call{Call: _e.mock.On("SaveTelegramUser", ctx, user)}
}

func (_c *MockRepository_SaveTelegramUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockRepository_SaveTelegramUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SaveTelegramUser_Call) Return(user1 domain.User, err error) *MockRepository_SaveTelegramUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_SaveTelegramUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (domain.User, error)) *MockRepository_SaveTelegramUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRequestStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateRequestStatus(ctx context.Context, requestID uuid.UUID, status domain.StatusType) error {
	ret := _mock.Called(ctx, requestID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequestStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.StatusType) error); ok {
		r0 = returnFunc(ctx, requestID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequestStatus'
type MockRepository_UpdateRequestStatus_Call struct {
	*mock.Call
}

// UpdateRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - status domain.StatusType
func (_e *MockRepository_Expecter) UpdateRequestStatus(ctx interface{}, requestID interface{}, status interface{}) *MockRepository_UpdateRequestStatus_Call {
	return &MockRepository_UpdateRequestStatus_Call{Call: _e.mock.On("UpdateRequestStatus", ctx, requestID, status)}
}

func (_c *MockRepository_UpdateRequestStatus_Call) Run(run func(ctx context.Context, requestID uuid.UUID, status domain.StatusType)) *MockRepository_UpdateRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.StatusType
		if args[2] != nil {
			arg2 = args[2].(domain.StatusType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateRequestStatus_Call) Return(err error) *MockRepository_UpdateRequestStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateRequestStatus_Call) RunAndReturn(run func(ctx context.Context, requestID uuid.UUID, status domain.StatusType) error) *MockRepository_UpdateRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}
