// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID          int32
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        *string
	PasswordHash string
	RoleID       int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
